services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: build/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
